version: "3.3"
services:
  postgresql:
    container_name: postgres
    image: postgres:latest
    build:
      context: ./database
      dockerfile: Dockerfile
    env_file:
      - ./database/database.env
    ports:
      - "5432:5432"

  #TimeLog-server:
  #  depends_on:
  #    - postgresql
  #  build: .
  #  image: "timelog-server:develop-0.0.2"
  #  container_name: "TimeLog-server"
  #  ports:
  #    - "8818:8818"